apiVersion: v1
kind: Service
metadata:
  name: clients-api-service
  labels:
    app: clients-api
    owner: anupam
    environment: dev
spec:
  selector:
    app: clients-api
  ports:
    - name: http
      port: 80
      targetPort: 5000
  type: ClusterIP
